### ISSUE TITLE
Add blob storage management

### ISSUE THREAD

**Issue by emiliogg84** [netadvantage/Liveschool#12]
Blob Storage allow the system to store large binary objects in a separate storage, different entities can point to a storage entry. The blob storage has the possibility to save, delete and retrieve files from the underlying storage.

Tasks:
- Add an Entity/ies to storage the data.
- Add an API controller to expose the methods.
- Add the mappings to the DAL.

**Comment by emiliogg84** [comment]
@gpedraza1990 review the SalesJet project to view how to implement a Blob Storage.

**Comment by jcesarsa** [comment]
OK...
